# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
self:
  wintr/auth/firebase:
    allowEmailPassword: true
  wintr/auth/ice:
    jwtSecret: bogus
    refreshExpirationTime: 1h
    accessExpirationTime: 1h
