# TODO: options need to be rechecked after automatic migration from v1 to v2.
version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - decorder
    - depguard
    - durationcheck
    - exhaustruct
    - gomoddirectives
    - gomodguard
    - importas
    - ireturn
    - nonamedreturns
    - promlinter
    - tagalign
    - testpackage
    - wsl
    - errcheck # TODO: check how to use it properly for v2.
    - testifylint # TODO: check how to use it properly for v2.
    - noinlineerr
    - embeddedstructfieldcheck
    - wsl_v5
    - unqueryvet
  settings:
    cyclop:
      max-complexity: 15
      package-average: 10
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      check-error-free-encoding: true
      report-no-exported: true
    funlen:
      lines: 30
      statements: 30
    gocognit:
      min-complexity: 15
    goconst:
      min-occurrences: 2
      numbers: true
      min: 2
      max: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        hugeParam:
          sizeThreshold: 32
        nestingReduce:
          bodyWidth: 4
        rangeExprCopy:
          sizeThreshold: 32
          skipTestFuncs: false
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: false
        tooManyResultsChecker:
          maxResults: 3
        truncateCmp:
          skipArchDependent: false
        underef:
          skipRecvDeref: false
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 15
    godot:
      scope: all
      exclude:
        - '^fixme:'
        - '^todo:'
        - '^TODO:'
        - 'SPDX-License-Identifier: ice License 1.0'
      capital: true
    goheader:
      template: 'SPDX-License-Identifier: ice License 1.0'
    gosec:
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: true
          per_char_threshold: "3.0"
          truncate: "32"
        global:
          audit: true
          nosec: true
          show-ignored: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
        shadow:
          strict: true
    grouper:
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
      type-require-grouping: true
      var-require-grouping: true
    lll:
      line-length: 160
    makezero:
      always: true
    nolintlint:
      require-explanation: true
      require-specific: true
    predeclared:
      qualified-name: true
    revive:
      confidence: 0.1
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: error
          disabled: true
        - name: datarace
          severity: error
          disabled: false
        - name: use-any
          severity: error
          disabled: false
        - name: comment-spacings
          arguments:
            - nolint
          severity: error
          disabled: false
        - name: argument-limit
          arguments:
            - 5
          severity: error
          disabled: false
        - name: atomic
          severity: error
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
            - "7"
          severity: error
          disabled: true
        - name: bare-return
          severity: error
          disabled: true
        - name: blank-imports
          severity: error
          disabled: true
        - name: bool-literal-in-expr
          severity: error
          disabled: false
        - name: call-to-gc
          severity: error
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 15
          severity: error
          disabled: false
        - name: confusing-naming
          severity: error
          disabled: false
        - name: confusing-results
          severity: error
          disabled: false
        - name: constant-logical-expr
          severity: error
          disabled: false
        - name: context-as-argument
          severity: error
          disabled: false
        - name: context-keys-type
          severity: error
          disabled: false
        - name: cyclomatic
          arguments:
            - 15
          severity: error
          disabled: false
        - name: deep-exit
          severity: error
          disabled: true
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - return
          severity: error
          disabled: false
        - name: dot-imports
          severity: error
          disabled: false
        - name: duplicated-imports
          severity: error
          disabled: false
        - name: early-return
          severity: error
          disabled: false
        - name: empty-block
          severity: error
          disabled: false
        - name: empty-lines
          severity: error
          disabled: false
        - name: error-naming
          severity: error
          disabled: false
        - name: error-return
          severity: error
          disabled: false
        - name: error-strings
          severity: error
          disabled: false
        - name: errorf
          severity: error
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: error
          disabled: false
        - name: file-header
          arguments:
            - 'SPDX-License-Identifier: ice License 1.0'
          severity: error
          disabled: false
        - name: flag-parameter
          severity: error
          disabled: false
        - name: function-result-limit
          arguments:
            - 3
          severity: error
          disabled: false
        - name: function-length
          arguments:
            - 30
            - 30
          severity: error
          disabled: true
        - name: get-return
          severity: error
          disabled: false
        - name: identical-branches
          severity: error
          disabled: false
        - name: if-return
          severity: error
          disabled: false
        - name: increment-decrement
          severity: error
          disabled: false
        - name: indent-error-flow
          severity: error
          disabled: false
        - name: import-shadowing
          severity: error
          disabled: false
        - name: line-length-limit
          arguments:
            - 160
          severity: error
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: error
          disabled: true
        - name: modifies-parameter
          severity: error
          disabled: false
        - name: modifies-value-receiver
          severity: error
          disabled: false
        - name: nested-structs
          severity: error
          disabled: true
        - name: optimize-operands-order
          severity: error
          disabled: false
        - name: package-comments
          severity: error
          disabled: false
        - name: range
          severity: error
          disabled: false
        - name: range-val-in-closure
          severity: error
          disabled: false
        - name: range-val-address
          severity: error
          disabled: false
        - name: receiver-naming
          severity: error
          disabled: false
        - name: redefines-builtin-id
          severity: error
          disabled: false
        - name: string-of-int
          severity: error
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: error
          disabled: true
        - name: struct-tag
          severity: error
          disabled: false
        - name: superfluous-else
          severity: error
          disabled: false
        - name: time-equal
          severity: error
          disabled: false
        - name: time-naming
          severity: error
          disabled: false
        - name: var-naming
          arguments:
            - - ID
              - URL
            - - VM
          severity: error
          disabled: false
        - name: var-declaration
          severity: error
          disabled: false
        - name: unconditional-recursion
          severity: error
          disabled: false
        - name: unexported-naming
          severity: error
          disabled: false
        - name: unexported-return
          severity: error
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
          severity: error
          disabled: false
        - name: unnecessary-stmt
          severity: error
          disabled: false
        - name: unreachable-code
          severity: error
          disabled: false
        - name: unused-parameter
          severity: error
          disabled: false
        - name: unused-receiver
          severity: error
          disabled: false
        - name: useless-break
          severity: error
          disabled: false
        - name: waitgroup-by-value
          severity: error
          disabled: false
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    tagliatelle:
      case:
        rules:
          avro: camel
          bson: camel
          json: camel
          mapstructure: camel
          msgpack: camel
          xml: camel
          yaml: camel
        use-field-name: true
    varnamelen:
      min-name-length: 2
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - prefix(github.com/ice-blockchain)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ice-blockchain
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
