# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
self:
  wintr/notifications/push:
    bufferingEnabled: false
buffered:
  wintr/notifications/push:
    bufferingEnabled: true
