# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
self:
  wintr/connectors/storage/v2:
    runDDL: true
    credentials:
      user: bogus
      password: bogus
    primaryURL: postgresql://root:pass@localhost:5432/ice
    replicaURLs:
      - postgresql://root:pass@localhost:5432/ice
