# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
self:
  wintr/notifications/telegram:
    baseUrl: https://api.telegram.org
    linkPreviewOptions:
      isDisabled: false
    parseMode: HTML