# SPDX-License-Identifier: ice License 1.0

version: '3.7'

services:
  db%[1]v:
    image: tarantool/tarantool:latest
    pull_policy: always
    command: tarantool /opt/tarantool/init.lua
    ports:
      - %[1]v:%[1]v
    volumes:
      - ./init.lua:/opt/tarantool/init.lua